### ISSUE TITLE
Moss Key page on web

### ISSUE THREAD

**Issue by stephenprae** [kevinrae/mosskey#24] opened 2018-03-09 04:54 UTC
Following selection of character(s) and deletion of all, the complete list of potential taxa does not reappear.  if wishing to then select one of the taxa to view coded characters, the user must exit and re-enter the application.

**Comment by kevinrae** [comment] 2018-03-09 05:06
This is a duplicate of issue #2

**Closed as completed by kevinrae** 2018-03-09 05:06 UTC
Labels: duplicate
